theme: jekyll-theme-dinky


# Site settings
title: Research Blog
email: nicoledrakos@gmail.com
url: "https://ndrakos.github.io/blog/" # the base hostname & protocol for your site
twitter_username:
github_username:  ndrakos
